using Anivision.Core;
using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.Rendering.Universal;

namespace Anivision.Vision
{
    // Parent class for effects that modify the render pipeline
    public abstract class RendererEffect : MonoBehaviour
    {
        public VisionEffect Effect { get; } // The vision effect that corresponds to this renderer effect

        // Returns the renderer feature generated by this renderer effect, which is added to the pipeline
        public abstract ScriptableRendererFeature GetRendererFeature(VisionParameters parameters);
    }
}

